alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
# alias sprite='/home/tumi/.steam/debian-installation/steamapps/common/Aseprite/aseprite'
# alias sprites='/home/tumi/.steam/debian-installation/steamapps/common/Aseprite/aseprite'
alias openfile='gio open'
alias ..='cd ..'
alias clock='peaclock'
alias files='xdg-open .'
alias fuck='thefuck'
alias epub='epy'
alias gconf='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
