format = """
[](#2E63B3)\
$username\
[](bg:#394B66 fg:#2E63B3)\
$directory\
[](fg:#394B66 bg:#3C80E6)\
$git_branch\
$git_status\
[](fg:#3C80E6 bg:#83ACEA)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#83ACEA bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#2E63B3"
style_root = "bg:#2E63B3"
format = '[ ]($style)'

[directory]
style = "bg:#394B66"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "‥\\"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#83ACEA"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#83ACEA"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#83ACEA"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#3C80E6"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#3C80E6"
format = '[$all_status ]($style)'

[golang]
symbol = " "
style = "bg:#83ACEA"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#83ACEA"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#83ACEA"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#83ACEA"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#83ACEA"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#83ACEA"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#83ACEA"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#83ACEA"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'
